#spring.application.name=bt70_JPA_KANBAN

# 서버 포트번호
server:
  port: 8080

# 콘솔 ANSI tㅐㄱ상
spring:
  output:
    ansi:
      enabled: always

  #  thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_react?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

  #JPA 세팅
  jpa:
    show-sql: true  # JPA 에서 생성되는 SQL문 콜솔 출력
    properties:
      hibernate.format_sql: true   # 쿼리 포맷팅 출력

    hibernate:
      ddl-auto: update

  # security
  security:
    user:
      name: user1     # 디폴트 security username
      password: 1234   #  password


app:
  # 파일 업로드 경로
  upload:
    path: upload

  # 페이징 관련 세팅값
  pagination:
    write_pages: 6  # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 6   # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?