# 서버포트 번호
server:
  port: 8080

# 콘솔 ANSI 색상
spring:
  output:
    ansi:
      enabled: always

  # thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_react?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

  #JPA 세팅
  jpa:
    show-sql: true  # JPA 에서 생성되는 SQL문 콜솔 출력
    properties:
      hibernate.format_sql: true   # 쿼리 포맷팅 출력

    hibernate:
      ddl-auto: update

  # security
  security:
    user:
      name: user1     # 디폴트 security username
      password: 1234   #  password

    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 148208030996-ckfnonbv5uippt5n105bffun4bmrpuhs.apps.googleusercontent.com
            client-secret:
            scope:
              - email
              - profile

          facebook:
            client-id: 290270110033944  # 앱 ID
            client-secret:   # 앱 시크릿 코드
            scope:
              - email
              - public_profile

          naver:
            client-id: 3ctPVlHkLbqMr6VdseZe
            client-secret:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        # provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  # 파일 업로드 경로
  upload:
    path: upload

  # 페이징 관련 세팅값
  pagination:
    write_pages: 10  # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10   # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?

  # OAuth2
  oauth2:

    password: 1234

    # Kakao 로그인 관련 세팅값
    kakao:
      client-id:    # 앱 키
      redirect-uri: http://localhost:8080/oauth2/kakao/callback  # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token   # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me   # 사용자 profile 요청 URI




