# 서버 포트 번호
server:
  port: 8080


spring:
  # 콘솔 ANSI 색상
  output:
    ansi:
      enabled: always


  # H2 DB 콘솔 활성화
  h2:
    console: true


  # H2 db 접속 URL
  datasource:
    url: jdbc:h2:mem:test


  jpa:
    # 기본적으로 data.sql 은 Hibernate 가 초기화 되기전에 수행된다.
    # Hibernate 에서 생성한뒤 data.sql 이 수행되게 하려면 아래설정을 해주어야 한다
    defer-datasource-initialization: true


    # JPA에서 생성되는 SQL 문을 콘솔 출력
    show-sql: true


    # 쿼리가 훨씬 보기 좋게 정렬되어 로그 찍힌다
    properties:
      hibernate:
        format_sql: true
